### ISSUE TITLE
System.InvalidCastException error on startup

### ISSUE THREAD

**Issue by roanh47** [FancyWM/fancywm-issues#122]
**Describe the bug**
I get the following error when starting FancyWM:
`System.InvalidCastException: Specified cast is not valid.`

**To Reproduce**
1. I installed FancyWM from the Microsoft Store
2. I get the error on startup.

I have tried to reinstall multiple times, but I keep getting this exact error, and I don't know how to fix this issue.

**Expected behavior**
I expected FancyWM to open normally without a fatal error on startup.

**Screenshots**
<img width="350" alt="image" src="https://user-images.githubusercontent.com/110937298/183776332-e0f44be0-9381-4649-bde4-f8d3420dfa38.png">

**Desktop:**
 - OS: Windows 11 Home Insider Preview (Dev)
 - Version 22H2 64-bit (OS Build 25163.1010)
 - FancyWM version: v2.8.0

**Additional context**
Details:
```
System.InvalidCastException: Specified cast is not valid.
at WinMan.Windows.Com.IComServiceProvider10.QueryService(Guid& service, Guid& riid)
at WinMan.Windows.Win32VirtualDesktopService22449.Connect()
at WinMan.Windows.Win32VirtualDesktopService22449..ctor()
at WinMan.Windows.Win32Workspace.<get_VirtualDesktopManagerLazy>g__Init|49_0()
at WinMan.Windows.Win32Workspace.get_VirtualDesktopManagerLazy()
at WinMan.Windows.Win32Workspace.get_VirtualDesktopManager()
at FancyWM.MainWindow..ctor()
at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
```

**Comment by veselink1** [comment]
Hello, thanks for reporting. Windows Insider Preview builds are not officially supported.
