### ISSUE TITLE
Fatal error on startup of FancyWM

### ISSUE THREAD

**Issue by Positron010** [FancyWM/fancywm-issues#126]
**Describe the bug**
FancyWM doesn't start due to this fatal error

```
System.InvalidCastException: Specified cast is not valid.
   at WinMan.Windows.Com.IComServiceProvider10.QueryService(Guid& service, Guid& riid)
   at WinMan.Windows.Win32VirtualDesktopService22449.Connect()
   at WinMan.Windows.Win32VirtualDesktopService22449..ctor()
   at WinMan.Windows.Win32Workspace.<get_VirtualDesktopManagerLazy>g__Init|49_0()
   at WinMan.Windows.Win32Workspace.get_VirtualDesktopManagerLazy()
   at WinMan.Windows.Win32Workspace.get_VirtualDesktopManager()
   at FancyWM.MainWindow..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
```

**Comment by veselink1** [comment]
Thanks for reporting. Seems to be related to the new Windows 11 22H2 update which is not yet supported. FancyWM v2.9.0 has added checks to detect Windows Insider builds and not crash, however, certain features might not work.
