### ISSUE TITLE
OnlyOffice causes fancywm to error

### ISSUE THREAD

**Issue by pc-v2** [FancyWM/fancywm-issues#25]
**Describe the bug**

**To Reproduce**
1. Open OnlyOffice
3. Click any area in onlyoffice
> ![image](https://user-images.githubusercontent.com/58063311/149508026-24607f9a-a4e7-4fcf-975a-71f22d1ddaaa.png)

**Expected behavior**
FancyWM does not get exception 
**Screenshots**
![image](https://user-images.githubusercontent.com/58063311/149508106-36687e63-c85a-4298-9a48-ce5caeaf6d44.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 22000.434

**Additional context**
```
System.ComponentModel.Win32Exception (22): {03541046: DocEditorsWindowClass} does not support WM_GETMINMAXINFO!: The device does not recognize the command.
   at WinMan.Windows.ExceptionExtensions.WithMessage(Win32Exception e, String message)
   at WinMan.Windows.Win32Window.GetMinMaxSize()
   at WinMan.Windows.Win32Window.<get_MinSize>b__65_0()
   at WinMan.Windows.Win32Window.UseDefaults[T](Func`1 func, T defaultValue)
   at WinMan.Windows.Win32Window.get_MinSize()
   at FancyWM.TilingWorkspace.CanFitLossy(PanelNode parent, IWindow window)
   at FancyWM.TilingWorkspace.RegisterWindow(IWindow window, PanelNode parent, WindowNode anchor)
   at FancyWM.TilingWorkspace.RegisterWindow(IWindow window)
   at FancyWM.TilingService.DetectChanges(IWindow window)
   at FancyWM.TilingService.OnWindowPositionChanged(Object sender, WindowPositionChangedEventArgs e)
   at WinMan.Windows.Win32Window.<>c__DisplayClass128_0.<UpdatePositionAndNotify>b__0()
   at WinMan.Windows.Win32Window.UpdateConfiguration()
   at WinMan.Windows.Win32Window.OnPositionChanged()
   at WinMan.Windows.Win32Workspace.<>c__DisplayClass74_0.<OnWinEvent>b__7()
   at WinMan.Windows.Utilities.EventLoop.Run()
--- End of stack trace from previous location ---
   at FancyWM.Utilities.Dispatchers.<>c__DisplayClass4_0.<RethrowOnDispatcher>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at FancyWM.Startup.Main(String[] args) 
```

**Comment by veselink1** [comment]
Thanks for reporting this.

**Comment by veselink1** [comment]
Okay, I was able to briefly look into this. This is caused by the OnlyOffice window not supporting the WM_GETMINMAXINFO message, which is how Windows itself knows what the minimum (and maximum) window size is. FancyWM cannot manage such windows. 

FancyWM should detect this situation and automatically float the window, instead of crashing. Until this is implemented, I would suggest adding a rule for the process which created the window (Settings > Rules).

**Comment by pc-v2** [comment]
already set the rules to except process still error :/

> ![image](https://user-images.githubusercontent.com/58063311/150896886-56d978ca-df91-4698-8f8b-839d6b9e640f.png)
> ![image](https://user-images.githubusercontent.com/58063311/150896890-df08ebcf-4116-45fe-8375-7a8c6c2c7a4c.png)
>

**Comment by pc-v2** [comment]
it works!

**Comment by veselink1** [comment]
Great to hear. v2.5.0 has improved support for windows that do not support WM_MINMAXINFO. It can look buggy if the window is resized to be smaller than what it has been programmed to expect (and FancyWM has no way of knowing what that value is).
